import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./Components/Sidebar/Sidebar";
import GlobalStyles from "./Providers/GlobalStylesProvider";
import ContextProvider from "./Providers/ContextProvider";

const inter = Inter({ subsets: ["latin"] }); // Initialises the Inter font with a Latin subset

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; // Defines the metadata for the Next.js app

// Defines the RootLayer functional component
// The RootLayer serves as the layout for the entire app
export default function RootLayout({
  children, // Prop named 'children' has been defined which represents the content to be rendered within the layout
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link 
      rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" 
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" 
      crossOrigin="anonymous" 
      referrerPolicy="no-referrer" 
      />
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <GlobalStyles>
            <SideBar/>
            {children}
          </GlobalStyles>
        </ContextProvider>
        </body>
    </html>
  ); // Render the root HTML structure in English, using the body class dynamically and nesting child components within ContextProvider and GlobalStyles


}


